version: '3'
services:
  dev-db:
    image: postgres:latest
    container_name: dev-db
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env
  test-db:
    image: postgres:latest
    container_name: test-db
    ports:
      - '6501:5432'
    env_file:
      - ./.env.test
volumes:
  progresDB:
